package com.example.bobbysandroidstartersolution

object PokemonData {
    val samplePokemons = listOf(
        Pokemon(
            id = 0,
            name = "N",
            pokemonClassification = "The Best Pokemon Trainer :D",
            pokemonDescription = "You Said You Have A Dream… That Dream… Make It Come True!",
            eggGroup = "Human",
            type = listOf("Normal", "Dragon"),
            abilities = listOf("COOL ;)", "AWESOMENESS"),
            hiddenAbility = "UNSTOPPABLE",
            levelUpAttacks = listOf("Hyper Beam", "Giga Impact", "Dragon Rush", "Dragon Claw"),
            tmAttacks = listOf("Toxic", "Hail", "Blizzard", "Hidden Power"),
            eggMoves = listOf("Aura Sphere", "Dragon Pulse"),
            moveTutorAttacks = listOf("Sleep Talk", "Helping Hand"),
            malePercentage = 50.0f,
            femalePercentage = 50.0f,
            height = 0.1f,
            weight = 0.2f,
            baseHP = 40,
            baseAttack = 100,
            baseDefence = 154,
            baseSAttack = 250,
            baseSDefence = 154,
            baseSpeed = 100,
            imageUrl="drawable/n.png",
        ),

        Pokemon(
            id = 495,
            name = "Snivy",
            pokemonClassification = "The Grass Snake Pokémon",
            pokemonDescription = "Being exposed to sunlight makes its movements swifter. It uses vines more adeptly than its hands",
            eggGroup = "Field",
            type = listOf("Grass"),
            abilities = listOf("Overgrow"),
            hiddenAbility = "Contrary",
            levelUpAttacks = listOf("Tackle", "Leer", "Vine Whip", "Wrap", "Growth", "Leaf Tornado", "Leech Seed", "Mega Drain", "Slam", "Leaf Blade", "Coil", "Giga Drain", "Wring Out", "Gastro Acid", "Leaf Storm"),
            tmAttacks = listOf("Calm Mind", "Toxic", "Hidden Power", "Sunny Day", "Taunt", "Light Screen", "Protect", "Safeguard", "Frustration", "Solarbeam", "Return", "Double Team", "Reflect", "Aerial Ace", "Torment", "Facade", "Rest", "Attract", "Round", "Energy Ball", "Flash", "Swords Dance", "Grass Knot", "Swagger", "Substitute", "Cut"),
            eggMoves = listOf("Captivate", "Natural Gift", "Glare", "Iron Tail", "Magical Leaf", "Sweet Scent", "Mirror Coat", "Pursuit", "Mean Look", "Twister"),
            moveTutorAttacks = listOf("Aqua Tail", "Bind", "Gastro Acid", "Giga Drain", "Grass Pledge", "Iron Tail", "Knock Off", "Seed Bomb", "Sleep Talk", "Snatch", "Snore", "Synthesis", "Worry Seed"),
            malePercentage = 87.5f,
            femalePercentage = 12.5f,
            height = 0.6f,
            weight = 8.1f,
            baseHP = 45,
            baseAttack = 45,
            baseDefence = 55,
            baseSAttack = 45,
            baseSDefence = 55,
            baseSpeed = 63,
            imageUrl="drawable/a_snivy.png",
        ),

        Pokemon(
            id = 496,
            name = "Servine",
            pokemonClassification = "The Grass Snake Pokémon",
            pokemonDescription = "When it gets dirty, its leaves can't be used in photosynthesis, so it always keeps itself clean.",
            eggGroup = "Field",
            type = listOf("Grass"),
            abilities = listOf("Overgrow"),
            hiddenAbility = "Contrary",
            levelUpAttacks = listOf("Tackle", "Leer", "Vine Whip", "Wrap", "Leer", "Vine Whip", "Wrap", "Growth", "Leaf Tornado", "Leech Seed", "Mega Drain", "Slam", "Leaf Blade", "Coil", "Giga Drain", "Wring Out", "Gastro Acid", "Leaf Storm"),
            tmAttacks = listOf("Calm Mind", "Toxic", "Hidden Power", "Sunny Day", "Taunt", "Light Screen", "Protect", "Safeguard", "Frustration", "Solarbeam", "Return", "Double Team", "Reflect", "Aerial Ace", "Torment", "Facade", "Rest", "Attract", "Round", "Energy Ball", "Flash", "Swords Dance", "Grass Knot", "Swagger", "Substitute", "Cut"),
            eggMoves = listOf("Captivate", "Natural Gift", "Glare", "Iron Tail", "Magical Leaf", "Sweet Scent", "Mirror Coat", "Pursuit", "Mean Look", "Twister"),
            moveTutorAttacks = listOf("Aqua Tail", "Bind", "Gastro Acid", "Giga Drain", "Grass Pledge", "Iron Tail", "Knock Off", "Seed Bomb", "Sleep Talk", "Snatch", "Snore", "Synthesis", "Worry Seed"),
            malePercentage = 87.5f,
            femalePercentage = 12.5f,
            height = 0.8f,
            weight = 16.0f,
            baseHP = 60,
            baseAttack = 60,
            baseDefence = 75,
            baseSAttack = 60,
            baseSDefence = 75,
            baseSpeed = 83,
            imageUrl="drawable/servine.png",
        ),

        Pokemon(
            id = 497,
            name = "Serperior",
            pokemonClassification = "Regal Pokémon",
            pokemonDescription = "It only gives its all fighting against strong opponents who are not fazed by the glare from Serperior's noble eyes.",
            eggGroup = "Field",
            type = listOf("Grass"),
            abilities = listOf("Overgrow"),
            hiddenAbility = "Contrary",
            levelUpAttacks = listOf("Tackle", "Leer", "Vine Whip", "Wrap", "Growth", "Leaf Tornado", "Leech Seed", "Mega Drain", "Slam", "Leaf Blade", "Coil", "Giga Drain", "Wring Out", "Gastro Acid", "Leaf Storm"),
            tmAttacks = listOf("Calm Mind", "Toxic", "Hidden Power", "Sunny Day", "Taunt", "Light Screen", "Protect", "Safeguard", "Frustration", "Solarbeam", "Return", "Double Team", "Reflect", "Aerial Ace", "Torment", "Facade", "Rest", "Attract", "Round", "Energy Ball", "Flash", "Swords Dance", "Grass Knot", "Swagger", "Substitute", "Cut"),
            eggMoves = listOf("Captivate", "Natural Gift", "Glare", "Iron Tail", "Magical Leaf", "Sweet Scent", "Mirror Coat", "Pursuit", "Mean Look", "Twister"),
            moveTutorAttacks = listOf("Aqua Tail", "Bind", "Gastro Acid", "Giga Drain", "Grass Pledge", "Iron Tail", "Knock Off", "Seed Bomb", "Sleep Talk", "Snatch", "Snore", "Synthesis", "Worry Seed"),
            malePercentage = 87.5f,
            femalePercentage = 12.5f,
            height = 3.3f,
            weight = 63.0f,
            baseHP = 75,
            baseAttack = 75,
            baseDefence = 95,
            baseSAttack = 75,
            baseSDefence = 95,
            baseSpeed = 113,
            imageUrl="drawable/serperior.png",
        ),
        Pokemon(
            id = 498,
            name = "Tepig",
            pokemonClassification = "Fire Pig Pokémon",
            pokemonDescription = "It blows fire through its nose. When it catches a cold, the fire becomes pitch-black smoke instead.",
            eggGroup = "Field",
            type = listOf("Fire"),
            abilities = listOf("Blaze"),
            hiddenAbility = "Thick Fat",
            levelUpAttacks = listOf("Tackle", "Tail Whip", "Ember", "Odor Sleuth", "Defense Curl", "Flame Charge", "Smog", "Rollout", "Take Down", "Heat Crash", "Assurance", "Flamethrower", "Head Smash", "Roar"),
            tmAttacks = listOf("Toxic", "Hidden Power", "Sunny Day", "Taunt", "Hyper Beam", "Protect", "Frustration", "Return", "Dig", "Double Team", "Flamethrower", "Fire Blast", "Facade", "Flame Charge", "Rest", "Attract", "Round", "Echoed Voice", "Overheat", "Incinerate", "Will-O-Wisp", "Swagger", "Substitute", "Wild Charge", "Rock Smash", "Strength"),
            eggMoves = listOf("Body Slam", "Curse", "Endure", "Flame Burst", "Iron Tail", "Magnitude", "Sucker Punch", "Superpower", "Thrash", "Yawn"),
            moveTutorAttacks = listOf("Bounce", "Covet", "Endeavor", "Fire Pledge", "Headbutt", "Heat Wave", "Iron Tail", "Sleep Talk", "Snore", "Superpower", "Zen Headbutt"),
            malePercentage = 87.5f,
            femalePercentage = 12.5f,
            height = 0.5f,
            weight = 9.9f,
            baseHP = 65,
            baseAttack = 63,
            baseDefence = 45,
            baseSAttack = 45,
            baseSDefence = 45,
            baseSpeed = 45,
            imageUrl="drawable/a_tepig.png",
        ),

        Pokemon(
            id = 499,
            name = "Pignite",
            pokemonClassification = "Fire Pig Pokémon",
            pokemonDescription = "The more it eats, the more fuel it has to make the fire in its stomach stronger. This fills it with even more power.",
            eggGroup = "Field",
            type = listOf("Fire", "Fighting"),
            abilities = listOf("Blaze"),
            hiddenAbility = "Thick Fat",
            levelUpAttacks = listOf("Tackle", "Tail Whip", "Ember", "Odor Sleuth", "Defense Curl", "Flame Charge", "Smog", "Rollout", "Take Down", "Heat Crash", "Assurance", "Flamethrower", "Head Smash", "Roar"),
            tmAttacks = listOf("Toxic", "Hidden Power", "Sunny Day", "Taunt", "Hyper Beam", "Protect", "Frustration", "Return", "Dig", "Double Team", "Flamethrower", "Fire Blast", "Facade", "Flame Charge", "Rest", "Attract", "Round", "Echoed Voice", "Overheat", "Incinerate", "Will-O-Wisp", "Swagger", "Substitute", "Wild Charge", "Rock Smash", "Strength"),
            eggMoves = listOf("Body Slam", "Curse", "Endure", "Flame Burst", "Iron Tail", "Magnitude", "Sucker Punch", "Superpower", "Thrash", "Yawn"),
            moveTutorAttacks = listOf("Bounce", "Covet", "Endeavor", "Fire Pledge", "Headbutt", "Heat Wave", "Iron Tail", "Sleep Talk", "Snore", "Superpower", "Zen Headbutt"),
            malePercentage = 87.5f,
            femalePercentage = 12.5f,
            height = 1.0f,
            weight = 55.5f,
            baseHP = 90,
            baseAttack = 93,
            baseDefence = 55,
            baseSAttack = 70,
            baseSDefence = 55,
            baseSpeed = 55,
            imageUrl="drawable/pignite.png",
        ),

        Pokemon(
            id = 500,
            name = "Emboar",
            pokemonClassification = "Mega Fire Pig Pokémon",
            pokemonDescription = "It can throw a fire punch by setting its fists on fire with its fiery chin. It cares deeply about its friends.",
            eggGroup = "Field",
            type = listOf("Fire", "Fighting"),
            abilities = listOf("Blaze"),
            hiddenAbility = "Reckless",
            levelUpAttacks = listOf("Tackle", "Tail Whip", "Ember", "Odor Sleuth", "Defense Curl", "Flame Charge", "Smog", "Rollout", "Take Down", "Heat Crash", "Assurance", "Flamethrower", "Head Smash", "Roar"),
            tmAttacks = listOf("Toxic", "Hidden Power", "Sunny Day", "Taunt", "Hyper Beam", "Protect", "Frustration", "Return", "Dig", "Double Team", "Flamethrower", "Fire Blast", "Facade", "Flame Charge", "Rest", "Attract", "Round", "Echoed Voice", "Overheat", "Incinerate", "Will-O-Wisp", "Swagger", "Substitute", "Wild Charge", "Rock Smash", "Strength"),
            eggMoves = listOf("Body Slam", "Curse", "Endure", "Flame Burst", "Iron Tail", "Magnitude", "Sucker Punch", "Superpower", "Thrash", "Yawn"),
            moveTutorAttacks = listOf("Bounce", "Covet", "Endeavor", "Fire Pledge", "Headbutt", "Heat Wave", "Iron Tail", "Sleep Talk", "Snore", "Superpower", "Zen Headbutt"),
            malePercentage = 87.5f,
            femalePercentage = 12.5f,
            height = 1.6f,
            weight = 150.0f,
            baseHP = 110,
            baseAttack = 123,
            baseDefence = 65,
            baseSAttack = 100,
            baseSDefence = 65,
            baseSpeed = 65,
            imageUrl="drawable/emboar.png",
        ),


        Pokemon(
            id = 501, // Pokémon ID for Oshawott
            name = "Oshawott",
            pokemonClassification = "Sea Otter Pokémon",
            pokemonDescription = "The scalchop on its stomach isn't just used for battle—it can be used to break open hard berries as well.",
            eggGroup = "Field",
            type = listOf("Water"),
            abilities = listOf("Torrent"),
            hiddenAbility = "Shell Armor",
            levelUpAttacks = listOf("Tackle", "Tail Whip", "Water Gun", "Water Sport", "Focus Energy", "Razor Shell", "Fury Cutter", "Water Pulse", "Revenge", "Aqua Jet", "Encore", "Aqua Tail", "Retaliate", "Swords Dance", "Hydro Pump"),
            tmAttacks = listOf("Toxic", "Hail", "Hidden Power", "Taunt", "Ice Beam", "Blizzard", "Project", "Rain Dance", "Frustration", "Return", "Dig", "Double Team", "Aerial Ace", "Facade", "Rest", "Attract", "Round", "False Swipe", "Scald", "Fling", "Retaliate", "Swords Dance", "X-scissor", "Grass Knot", "Swagger", "Substitute", "Rock Smash", "Cut", "Surf", "Waterfall", "Dive"),
            eggMoves = listOf("Copycat", "Detect", "Air Slash", "Assurance", "Brine", "Night Slash", "Trump Card", "Screech"),
            moveTutorAttacks = listOf("Aqua Tail", "Covet", "Helping Hand", "Icy Wind", "Iron Tail", "Sleep Talk", "Snore", "Water Pledge"),
            malePercentage = 87.5f,
            femalePercentage = 12.5f,
            height = 0.5f, // Meters
            weight = 5.9f, // Kilograms
            baseHP = 55,
            baseAttack = 55,
            baseDefence = 45,
            baseSAttack = 63,
            baseSDefence = 45,
            baseSpeed = 45,
            imageUrl="drawable/a_oshawott.png",
        ),

        Pokemon(
            id = 502,
            name = "Dewott",
            pokemonClassification = "Discipline Pokémon",
            pokemonDescription = "Scalchop techniques differ from one Dewott to another. It never neglects maintaining its scalchops.",
            eggGroup = "Field",
            type = listOf("Water"),
            abilities = listOf("Torrent"),
            hiddenAbility = "Shell Armor",
            levelUpAttacks = listOf("Tackle", "Tail Whip", "Water Gun", "Water Sport", "Focus Energy", "Razor Shell", "Fury Cutter", "Water Pulse", "Revenge", "Aqua Jet", "Encore", "Aqua Tail", "Retaliate", "Swords Dance", "Hydro Pump"),
            tmAttacks = listOf("Toxic", "Hail", "Hidden Power", "Taunt", "Ice Beam", "Blizzard", "Project", "Rain Dance", "Frustration", "Return", "Dig", "Double Team", "Aerial Ace", "Facade", "Rest", "Attract", "Round", "False Swipe", "Scald", "Fling", "Retaliate", "Swords Dance", "X-scissor", "Grass Knot", "Swagger", "Substitute", "Rock Smash", "Cut", "Surf", "Waterfall", "Dive"),
            eggMoves = listOf("Copycat", "Detect", "Air Slash", "Assurance", "Brine", "Night Slash", "Trump Card", "Screech"),
            moveTutorAttacks = listOf("Aqua Tail", "Covet", "Helping Hand", "Icy Wind", "Iron Tail", "Sleep Talk", "Snore", "Water Pledge"),
            malePercentage = 87.5f,
            femalePercentage = 12.5f,
            height = 0.8f,
            weight = 24.5f,
            baseHP = 75,
            baseAttack = 75,
            baseDefence = 60,
            baseSAttack = 83,
            baseSDefence = 60,
            baseSpeed = 60,
            imageUrl="drawable/dewott.png",
        ),

        Pokemon(
            id = 503,
            name = "Samurott",
            pokemonClassification = "Formidable Pokémon",
            pokemonDescription = "One swing of the sword incorporated in its armor can fell an opponent. A simple glare from one of them quiets everybody.",
            eggGroup = "Field",
            type = listOf("Water"),
            abilities = listOf("Torrent"),
            hiddenAbility = "Shell Armor",
            levelUpAttacks = listOf("Tackle", "Tail Whip", "Water Gun", "Water Sport", "Focus Energy", "Razor Shell", "Fury Cutter", "Water Pulse", "Revenge", "Aqua Jet", "Encore", "Aqua Tail", "Retaliate", "Swords Dance", "Hydro Pump"),
            tmAttacks = listOf("Toxic", "Hail", "Hidden Power", "Taunt", "Ice Beam", "Blizzard", "Project", "Rain Dance", "Frustration", "Return", "Dig", "Double Team", "Aerial Ace", "Facade", "Rest", "Attract", "Round", "False Swipe", "Scald", "Fling", "Retaliate", "Swords Dance", "X-scissor", "Grass Knot", "Swagger", "Substitute", "Rock Smash", "Cut", "Surf", "Waterfall", "Dive"),
            eggMoves = listOf("Copycat", "Detect", "Air Slash", "Assurance", "Brine", "Night Slash", "Trump Card", "Screech"),
            moveTutorAttacks = listOf("Aqua Tail", "Covet", "Helping Hand", "Icy Wind", "Iron Tail", "Sleep Talk", "Snore", "Water Pledge"),
            malePercentage = 87.5f,
            femalePercentage = 12.5f,
            height = 1.5f,
            weight = 94.6f,
            baseHP = 95,
            baseAttack = 100,
            baseDefence = 85,
            baseSAttack = 108,
            baseSDefence = 70,
            baseSpeed = 70,
            imageUrl="drawable/samurott.png",
        ),
    )
}
